name: Deliver Icons to Spark Repo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "build/web/dist/spark/icons/**"

jobs:
  deliver_icons_to_spark_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deliver Icons To Spark Web
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: build/web/dist/spark/icons
          destination-github-username: "adevinta"
          destination-repository-name: "spark"
          user-email: ${{ secrets.API_GITHUB_COMMIT_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: chore-updated-icons
          create-target-branch-if-needed: true
          target-directory: "packages/components/icons/assets"
