name: "📤 Deliver icons to Adevinta/spark"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "assets/spark/icons/**"

jobs:
  deliver_icons_to_spark_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Tokens
        run: npm run build
      - name: Deliver Icons To Spark Web
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_SPARK_WEB }}
        with:
          source-directory: build/web/dist/spark/icons
          destination-github-username: "adevinta"
          destination-repository-name: "spark"
          user-email: ${{ secrets.API_GITHUB_COMMIT_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: chore-updated-icons
          create-target-branch-if-needed: true
          target-directory: "packages/components/icons/assets"
