name: '🤖 spark-android svg2avd'

on:
  pull_request:
    branches: ["main", "hotfix/*"]

jobs:

  svg2avd:
    runs-on: ubuntu-latest
    env:
      DIST: 'build/android/dist/spark/icons'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
          cache: 'npm'
      - name: 'Install svgo'
        run: npm -g install svgo
      - name: 'Cleanup dist'
        run: |
          rm -rf "$DIST"
          mkdir -p "$DIST"
      - name: 'Run svg2avd.main.kts'
        run: ./spark-android/scripts/svg2avd/svg2avd.main.kts --input="assets/spark/icons" --output="$DIST" --prefix="spark_icons_" --copyright="spark-android/scripts/svg2avd/COPYRIGHT.xml"
