name: '🤖 spark-android svg2avd'

on:
  pull_request:
    branches: ["main", "hotfix/*"]

jobs:

  svg2avd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./spark-android/scripts/svg2avd/svg2avd.main.kts --help
